<?xml version="1.0"?>
<robot name="sparke" xmlns:xacro="http://ros.org/wiki/xacro">
	<!-- Constants -->
  <xacro:property name="base_length" value="0.254"/>
	<xacro:property name="base_width" value="0.11"/>
  <xacro:property name="base_height" value="0.065"/>

  <xacro:property name="shoulder_length" value="0.034"/>
	<xacro:property name="shoulder_width" value="0.0635"/>
  <xacro:property name="shoulder_height" value="0.013"/>

  <xacro:property name="leg_length" value="0.125"/>
	<xacro:property name="leg_width" value="0.040"/>
  <xacro:property name="leg_height" value="0.027"/>
  
  <xacro:property name="elbow_radius" value="0.0135"/>
	<xacro:property name="elbow_width" value="0.040"/>

  <xacro:property name="wrist_length" value="0.135"/>
	<xacro:property name="wrist_width" value="0.0325"/>
  <xacro:property name="wrist_height" value="0.015"/>

  <xacro:property name="foot_radius" value="0.015"/>
	<xacro:property name="foot_width" value="0.0325"/>

  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>


	<!-- Robot Base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Body">
        <color rgba="0 0.5 0.5 1"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="1.0" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <gazebo reference="base_link">
      <mu>50</mu>
      <mu2>25</mu2>
      <kp value="50000.0"/>
      <kd value="0.05"/>
      <dampingFactor value="0.0"/>
    </gazebo>

	<!-- Robot Footprint -->
  <link name="base_footprint">
    <xacro:box_inertia m="1.0" w="${base_width}" d="${base_length}" h="${base_height}"/>
  </link>

  <gazebo reference="base_footprint">
      <mu>50</mu>
      <mu2>25</mu2>
      <kp value="50000.0"/>
      <kd value="0.05"/>
      <dampingFactor value="0.0"/>
  </gazebo>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <!-- Shoulders -->
  <xacro:macro name="shoulder" params="prefix x_reflect y_reflect x_pos y_pos z_pos">
    <link name="${prefix}_b2s_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${shoulder_length} ${shoulder_width} ${shoulder_height}"/>
        </geometry>
        <material name="Shoulder">
          <color rgba="0 0.6 0.6 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <box size="${shoulder_length} ${shoulder_width} ${shoulder_height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="1.0" w="${shoulder_width}" d="${shoulder_length}" h="${shoulder_height}"/>

    </link>

    <joint name="${prefix}_b2s_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${prefix}_b2s_link"/>
      <origin xyz="${(x_pos - (shoulder_length/25)) * x_reflect} ${(y_pos + (shoulder_width/2)) * y_reflect} ${z_pos - (shoulder_height/2)}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
      <limit effort="1000" lower="0" upper="${pi/4}" velocity="0.0"/>
      <dynamics damping="0" friction="1"/>
    </joint>

    <gazebo reference="${prefix}_b2s_link">
      <mu>50</mu>
      <mu2>25</mu2>
      <kp value="50000.0"/>
      <kd value="0.05"/>
      <dampingFactor value="0.0"/>
    </gazebo>

    <link name="${prefix}_shoulder_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${shoulder_length} ${shoulder_width} ${shoulder_height}"/>
        </geometry>
        <material name="Shoulder">
          <color rgba="0 0.6 0.6 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <box size="${shoulder_length} ${shoulder_width} ${shoulder_height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="1.0" w="${shoulder_width}" d="${shoulder_length}" h="${shoulder_height}"/>

    </link>

    <joint name="${prefix}_shoulder_joint" type="revolute">
      <parent link="${prefix}_b2s_link"/>
      <child link="${prefix}_shoulder_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="1000" lower="${-pi/2}" upper="${pi/2}" velocity="0.0"/>
      <dynamics damping="0" friction="1"/>
    </joint>

    <gazebo reference="${prefix}_shoulder_link">
      <mu>50</mu>
      <mu2>25</mu2>
      <kp value="50000.0"/>
      <kd value="0.05"/>
      <dampingFactor value="0.0"/>
    </gazebo>
  </xacro:macro>

  <!-- Legs -->
  <xacro:macro name="leg" params="prefix x_reflect y_reflect x_pos y_pos z_pos">
    <link name="${prefix}_leg_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${leg_length} ${leg_width} ${leg_height}"/>
        </geometry>
        <material name="Body">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <box size="${leg_length} ${leg_width} ${leg_height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="1.0" w="${leg_width}" d="${leg_length}" h="${leg_height}"/>
      
    </link>

    <gazebo reference="${prefix}_leg_link">
      <mu>50</mu>
      <mu2>25</mu2>
      <kp value="50000.0"/>
      <kd value="0.05"/>
      <dampingFactor value="0.0"/>
    </gazebo>

    <joint name="${prefix}_leg_joint" type="fixed">
      <parent link="${prefix}_shoulder_link"/>
      <child link="${prefix}_leg_link"/>
      <origin xyz="${(x_pos - (leg_length/25)) * x_reflect} ${(y_pos + (leg_width/2)) * y_reflect} ${z_pos - (leg_height/2)}" rpy="0 ${-pi/4} 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <link name="${prefix}_elbow_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
        <geometry>
            <cylinder radius="${elbow_radius}" length="${elbow_width}"/>
        </geometry>
        <material name="Body">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
          <cylinder radius="${elbow_radius}" length="${elbow_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="1.0" r="${elbow_radius}" h="${elbow_width}"/>

    </link>

    <gazebo reference="${prefix}_elbow_link">
      <mu>50</mu>
      <mu2>25</mu2>
      <kp value="50000.0"/>
      <kd value="0.05"/>
      <dampingFactor value="0.0"/>
    </gazebo>

    <joint name="${prefix}_elbow_joint" type="revolute">
      <parent link="${prefix}_leg_link"/>
      <child link="${prefix}_elbow_link"/>
      <origin xyz="${-leg_length/2} 0 0" rpy="0 0 ${pi/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="1000" lower="${-pi/2}" upper="${pi/2}" velocity="0.0"/>
      <dynamics damping="0" friction="1"/>
    </joint>
  </xacro:macro>

  <!-- Wrists -->
  <xacro:macro name="wrist" params="prefix x_reflect y_reflect x_pos y_pos z_pos">
    <link name="${prefix}_wrist_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <box size="${wrist_length} ${wrist_width} ${wrist_height}"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <box size="${wrist_length} ${wrist_width} ${wrist_height}"/>
        </geometry>
      </collision>

      <xacro:box_inertia m="1.0" w="${wrist_width}" d="${wrist_length}" h="${wrist_height}"/>
    </link>

    <gazebo reference="${prefix}_wrist_link">
      <mu>50</mu>
      <mu2>25</mu2>
      <kp value="50000.0"/>
      <kd value="0.05"/>
      <dampingFactor value="0.0"/>
    </gazebo>

    <joint name="${prefix}_wrist_joint" type="fixed">
      <parent link="${prefix}_elbow_link"/>
      <child link="${prefix}_wrist_link"/>
      <origin xyz="0 0 ${-wrist_length/2}" rpy="0 ${pi/2} ${pi/2}"/>
      <axis xyz="0 1 0"/>
    </joint>

    <link name="${prefix}_foot_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${foot_radius}" length="${foot_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <cylinder radius="${foot_radius}" length="${foot_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="1.0" r="${foot_radius}" h="${foot_width}"/>
    </link>

    <gazebo reference="${prefix}_foot_link">
      <mu>50</mu>
      <mu2>25</mu2>
      <kp value="50000.0"/>
      <kd value="0.05"/>
      <dampingFactor value="0.0"/>
    </gazebo>

    <joint name="${prefix}_foot_joint" type="fixed">
      <parent link="${prefix}_wrist_link"/>
      <child link="${prefix}_foot_link"/>
      <origin xyz="${wrist_length/2} 0 0" rpy="0 ${pi/2} ${pi/2}"/>
      <axis xyz="0 1 0"/>
    </joint>    
  </xacro:macro>

  <xacro:shoulder prefix="fl" x_reflect="1" y_reflect="1" x_pos="0.101" y_pos="${base_width/2}" z_pos="${base_height/2}"/>
  <xacro:shoulder prefix="fr" x_reflect="1" y_reflect="-1" x_pos="0.101" y_pos="${base_width/2}" z_pos="${base_height/2}"/>
  <xacro:shoulder prefix="br" x_reflect="-1" y_reflect="-1" x_pos="0.101" y_pos="${base_width/2}" z_pos="${base_height/2}"/>
  <xacro:shoulder prefix="bl" x_reflect="-1" y_reflect="1" x_pos="0.101" y_pos="${base_width/2}" z_pos="${base_height/2}"/>

  <xacro:leg prefix="fl" x_reflect="1" y_reflect="1" x_pos="${-(leg_length/2)+(shoulder_length*0.9)}" y_pos="${-leg_width/2}" z_pos="${-(leg_length/4)-(shoulder_height/4)}"/>
  <xacro:leg prefix="fr" x_reflect="1" y_reflect="1" x_pos="${-(leg_length/2)+(shoulder_length*0.9)}" y_pos="${-leg_width/2}" z_pos="${-(leg_length/4)-(shoulder_height/4)}"/>
  <xacro:leg prefix="br" x_reflect="1" y_reflect="1" x_pos="${-(leg_length/2)+(shoulder_length*0.9)}" y_pos="${-leg_width/2}" z_pos="${-(leg_length/4)-(shoulder_height/4)}"/>
  <xacro:leg prefix="bl" x_reflect="1" y_reflect="1" x_pos="${-(leg_length/2)+(shoulder_length*0.9)}" y_pos="${-leg_width/2}" z_pos="${-(leg_length/4)-(shoulder_height/4)}"/>

  <xacro:wrist prefix="fl" x_reflect="1" y_reflect="1" x_pos="0" y_pos="0" z_pos="0"/>
  <xacro:wrist prefix="fr" x_reflect="1" y_reflect="1" x_pos="0" y_pos="0" z_pos="0"/>
  <xacro:wrist prefix="br" x_reflect="1" y_reflect="1" x_pos="0" y_pos="0" z_pos="0"/>
  <xacro:wrist prefix="bl" x_reflect="1" y_reflect="1" x_pos="0" y_pos="0" z_pos="0"/>

  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>

    <joint name="fl_elbow_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="fr_elbow_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="bl_elbow_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="br_elbow_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="fl_b2s_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="fr_b2s_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="bl_b2s_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="br_b2s_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="fl_shoulder_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="fr_shoulder_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="bl_shoulder_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
    <joint name="br_shoulder_joint">
      <command_interface name="position">
        <param name="min">-1.57</param>
        <param name="max">1.57</param>
      </command_interface>
      <state_interface name="position">
        <param name="initial_value">0.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <robot_sim_type>gazebo_ros2_control/GazeboSystem</robot_sim_type>
      <parameters>$(find sparke_description)/params/simple_controller.yaml</parameters>
    </plugin>
  </gazebo>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="fl_elbow_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="fr_elbow_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran3">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="bl_elbow_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor3">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran4">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="br_elbow_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor4">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran5">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="fl_b2s_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor5">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran6">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="fr_b2s_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor6">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran7">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="bl_b2s_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor7">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran8">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="br_b2s_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor8">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran9">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="fl_shoulder_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor9">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran10">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="fr_shoulder_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor10">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran11">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="bl_shoulder_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor11">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  <transmission name="tran12">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="br_shoulder_joint">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor12">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
