version: "3.8"
services:
  sparke:
    image: infiniteecho/sparke
    runtime: nvidia
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.sparke
    volumes:
      - "//dev://dev"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    network_mode: host
    pid: host
    privileged: true
    stop_grace_period: 1s
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
  sparke_dev:
    build:
      args:
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
      context: .
      dockerfile: dockerfiles/Dockerfile.sparke_dev
    container_name: sparke_dev
    runtime: nvidia
    environment:
      DISPLAY: :1
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      UID: ${UID}
      GID: ${GID}
      XAUTHORITY: /home/${USER}/.Xauthority
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: graphics,utility
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/opt/ros/ws
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - gazebo-cache:${HOME}/.gazebo
    user: ${UID}:${GID}
    privileged: true
    network_mode: host
    pid: host
    command: bash
    working_dir: /opt/ros/ws
volumes:
  gazebo-cache: